gridWorkingDir:         workingdir
gridOutputDir:          outputdir_13c_2runs_noSkim_part1
aliROOTVersion:         v5-09-44-1
aliPhysicsVersion:      vAN-20190109-1
#package:                fastjet::v3.2.1_1.024-alice3-1
#package:                cgal::v4.6.3-1
#package:                boost::v1.59.0-22
#package:                MPFR::v3.1.3-3
#package:                GMP::v6.0.0-1
3package:                GCC-Toolchain::v4.9.3-alice3-9
gridDataDir:            /alice/data/2013/LHC13c
dataPattern:            /pass4/*/AliESDs.root
runPrefix:              000
runNumber:             [195529, 195531]#part1
#runNumber:	       [195566, 195567]#part2
#runNumber:	       [195568, 195592]#part3
#runNumber:	       [195593, 195596]#part4
#runNumber:	       [195633, 195635]#part5
#runNumber:	       [195644, 195673]#part6
#runNumber:	       [195675, 195677]#part7
emcalCorrection:                emcal_correction.yaml
emcalGeometryFilename:          geometry_2015.root
emcalLocal2MasterFilename:      EMCALlocal2master.root
splitMaxInputFileNumber:        30.0