gridWorkingDir:         workingdir2
gridOutputDir:          outputdir_13f_1runs_noSkim_test_newRoot5_newEmcalCorrection_wNonLin
aliROOTVersion:         v5-09-54a-2
aliPhysicsVersion:      vAN-20200629-1
package:                fastjet::v3.2.1_1.024-alice3-71
package:                cgal::4.6.3-39
package:                boost::v1.72.0-alice1-11
package:                MPFR::v3.1.3-5
package:                GMP::v6.0.0-34
package:                GCC-Toolchain::v7.3.0-alice2-5
gridDataDir:            /alice/data/2013/LHC13f
dataPattern:            /pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[196608]
emcalCorrection:                emcal_correction_nonLin.yaml
emcalGeometryFilename:          geometry_2015.root
emcalLocal2MasterFilename:      EMCALlocal2master.root
splitMaxInputFileNumber:        30.0