gridWorkingDir:			workingdir
gridOutputDir:			outputdir_15o_jetSkimMin20GeV_kClusterizerv2
aliROOTVersion:			v5-09-44-1
aliPhysicsVersion:		vAN-20190109-1
package:			fastjet::v3.2.1_1.024-alice3-7
package:			cgal::v4.6.3-28
package:			boost::v1.59.0-22
package:			MPFR::v3.1.3-3
package:			GMP::v6.0.0-1
package:			GCC-Toolchain::v4.9.3-alice3-9
gridDataDir:		    	/alice/data/2015/LHC15o
dataPattern:		    	/pass1/*/AliESDs.root
runPrefix:		    	000
runNumber:		    	246945
emcalCorrection:	    	emcal_correction_PbPb.yaml
physicsSelection:	    	true
physicsSelectionMCAnalysis: 	false
physicsSelectionPileupCut:  	true
emcalGeometryFilename:	    	geometry_2015.root
emcalLocal2MasterFilename:  	EMCALlocal2master.root
splitMaxInputFileNumber:    	5
skimJetMinPt1:		    	20
skimJetMinPt2:		    	20