gridWorkingDir:         workingdir
gridOutputDir:          outputdir_17g6a3_pthat1_1run
aliROOTVersion:         v5-09-44-1
aliPhysicsVersion:      vAN-20190109-1
package:                fastjet::v3.2.1_1.024-alice3-7
package:                cgal::v4.6.3-28
package:                boost::v1.59.0-22
package:                MPFR::v3.1.3-3
package:                GMP::v6.0.0-1
package:                GCC-Toolchain::v4.9.3-alice3-9
gridDataDir:            /alice/sim/2017/LHC17g6a3/1
dataPattern:            */*/AliESDs.root
runNumber:              [195872]
runPrefix:
emcalCorrection:	emcal_correctionMC.yaml
emcalGeometryFilename:	geometry_2015.root
emcalLocal2MasterFilename: EMCALlocal2master.root
